FROM node:18-alpine

# définit le dossier 'app' comme dossier de travail
WORKDIR /app

# Copy 'package.json' and 'package-lock.json' (if they exist)
COPY package*.json ./

# copie les fichiers et dossiers du projet dans le dossier de travail (par exemple : le dossier 'app')
COPY ./ ./

# Install project dependencies
RUN npm install

# Run in dev mode
CMD [ "npm", "run", "start" ]

