version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    networks:
      report_calculation_report_bridge:
        ipv4_address: 169.254.6.5
        aliases:
          - "report-dashboard.portafolio"
    ports:
      - 80:80
      - 443:443  
    volumes:
      - ./:/app/
      - /app/node_modules
      - ./resources/nginx_prod.conf:/etc/nginx/conf.d/default.conf
      - ./resources/nginx_prod_ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./resources/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./resources/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./resources/dhparam.pem:/etc/ssl/certs/dhparam.pem

networks:
  report_calculation_report_bridge:
    external: true